name: Deploy Hugo Site

on:
  push:
    branches:
      - main
    paths:
      - 'apps/dannowak/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (Full History)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all files are checked out

      - name: Verify Repository Structure
        run: ls -R
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: |
          if [ ! -d "apps/dannowak" ]; then
            echo "Error: Directory apps/dannowak not found!"
            exit 1
          fi
          cd apps/dannowak
          hugo --minify

      - name: Deploy to S3
        run: |
          aws s3 sync apps/dannowak/public/ s3://dannowak-hugo-site --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1Y71PO1PNFWM5 --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
